name: Generate snake animation

on:
  schedule: # Execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step 1: Generate the snake SVG with customized light mode palette
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-light

      # Step 2: Inject CSS to enhance the look and feel of the animation
      - name: Add custom CSS for styling
        run: |
          echo "<style>
            svg {
              width: 100%;
              height: auto;
              background-color: #f5f5f5;
              border-radius: 10px;
            }
            .snake {
              fill: #4CAF50; /* Snake color: green */
            }
            .dot {
              fill: #FF6347; /* Dots color: tomato */
            }
            .background {
              fill: #FFFFFF; /* Background color: white */
            }
          </style>" > dist/snake.css

      # Step 3: Push the generated SVG and CSS to the output branch
      - name: Push snake.svg and CSS to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
